#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

enum PS_OP {
  SET_TASK_STATUS,
  GET_TASK_STATUS,
  REGISTER_TASK,
  GET_NUM_CONNS,
  GET_LAST_TIME_ERROR
};

enum PS_MSG { 
  CREATE_TENSOR_MSG = 1000,
  GET_TENSOR_MSG,
  GET_SPARSE_TENSOR_MSG,
  ADD_TENSOR_MSG,
};

#define MAGIC_NUMBER (0x1337)

#endif // _CONSTANTS_H_
